/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Reloj;
import clases.sonido;
import clases.txtDinamico;
import java.awt.Color;
import java.awt.Image;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Samuel David Ortiz
 */
public class ArbolGeneral extends javax.swing.JFrame {

    /**
     * Creates new form ArbolGeneral
     */
    private JLabel titulo;

    private ImageIcon Img;
    private Icon icono;
    
    Reloj reloj = new Reloj();

    public ArbolGeneral() {
        sonido soundClass = new sonido();
        soundClass = new sonido();
        soundClass.tiposonido(0);
        soundClass.start();
        
        initComponents();
        GUI();
        
        reloj.setLblReloj(lblReloj);
        reloj.start();

        lblReloj.setBackground(Color.black);
        lblReloj.setOpaque(true);
    }

    public void GUI() {

        // <editor-fold defaultstate="collapsed" desc="Escudo UMG">
        titulo = new JLabel();
        titulo.setSize(140, 140);
        titulo.setLocation(5, 5);
        Img = new ImageIcon(getClass().getResource("/images/umg.png"));
        //Img = new ImageIcon("./src/images/umg.png");
        icono = new ImageIcon(Img.getImage().getScaledInstance(140, 140,
                Image.SCALE_DEFAULT));

        titulo.setIcon(icono);
        titulo.setVisible(true);
        pnlTitulo.add(titulo, 0);
        // </editor-fold> 

        // <editor-fold defaultstate="collapsed" desc="Texto dinamico">
        String mensaje = "BIENVENIDO AL ARBOL DEL PRIMER PARCIAL 2022 ";
        txtDinamico texto = null;
        try {
            texto = new txtDinamico(mensaje, 300, lblTexto, new JLabel());
        } catch (Exception ex) {
            System.out.println("Error");
            Logger.getLogger(txtDinamico.class.getName()).log(Level.SEVERE, null, ex);
        }
        texto.start();
        // </editor-fold>  
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/tree.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtArbol = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arbol");

        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(788, 160));

        lblTexto.setText("jLabel1");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblReloj.setBackground(new java.awt.Color(0, 0, 0));
        lblReloj.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(102, 255, 0));
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("00:00:00");
        lblReloj.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                    .addContainerGap(618, Short.MAX_VALUE)
                    .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 15, 15));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("A");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("B");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("E");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("K");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("L");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("F");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("G");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("D");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("H");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("M");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("I");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("J");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jtArbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jtArbol);

        jPanel1.add(jScrollPane1);

        jPanel2.setLayout(new java.awt.GridLayout(8, 1, 15, 15));
        jPanel2.add(lblValor);

        txtValor.setToolTipText("Escriba lo que quiere agregar al árbol");
        jPanel2.add(txtValor);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);
        jPanel2.add(jSeparator1);

        btnLimpiar.setText("Limpiar arbol");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar);

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        try {
            DefaultTreeModel modeloArbol = (DefaultTreeModel) jtArbol.getModel();
            modeloArbol.setRoot(null);

            JOptionPane.showMessageDialog(null, "Se ha limpiado el árbol");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en funcion btnLimpiarActionPerformed(): " + ex.getMessage());
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try {
            TreeSelectionModel tsm = jtArbol.getSelectionModel();

            if (tsm.getSelectionCount() > 0) {
                DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jtArbol.getSelectionPath().getLastPathComponent();

                DefaultMutableTreeNode nodoNuevo = new DefaultMutableTreeNode(txtValor.getText());
                nodoSeleccionado.add(nodoNuevo);

                TreePath rutaNodo = new TreePath(nodoSeleccionado.getPath());

                DefaultTreeModel modeloArbol = (DefaultTreeModel) jtArbol.getModel();
                modeloArbol.reload();

                jtArbol.setSelectionPath(rutaNodo);
                jtArbol.expandPath(rutaNodo);
                //txtConsola.setText(txtConsola.getText() + "Nodo agregado: " + txtValor.getText() + " en: " +  rutaNodo.toString() + System.lineSeparator());

            } else {
                if (txtValor.getText().length() <= 0) {
                    throw new Exception("El valor no puede estar en blanco, por favor ingresa algo");
                }

                DefaultMutableTreeNode nodoRaiz = new DefaultMutableTreeNode(txtValor.getText());
                DefaultTreeModel modeloArbol = (DefaultTreeModel) jtArbol.getModel();
                modeloArbol.setRoot(nodoRaiz);

                //txtConsola.setText(txtConsola.getText() + "Nodo RAÍZ agregado: " + txtValor.getText() + System.lineSeparator());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            //txtConsola.setText(txtConsola.getText() + "Error en btnAgregarActionPerformed(): " + ex.getMessage() + System.lineSeparator());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            TreeSelectionModel tsm = jtArbol.getSelectionModel();
            if (tsm.getSelectionCount() <= 0) {
                throw new Exception("Ningún nodo seleccionado, para editar debes seleccionar uno");
            }

            if (txtValor.getText().length() <= 0) {
                throw new Exception("El valor no puede estar en blanco, por favor ingresa algo");
            }

            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jtArbol.getSelectionPath().getLastPathComponent();
            nodoSeleccionado.setUserObject(txtValor.getText());

            TreePath rutaNodo = new TreePath(nodoSeleccionado.getPath());

            DefaultTreeModel modeloArbol = (DefaultTreeModel) jtArbol.getModel();
            modeloArbol.reload();

            jtArbol.setSelectionPath(rutaNodo);
            jtArbol.expandPath(rutaNodo);

            //txtConsola.setText(txtConsola.getText() + "Nodo modificado, nuevo valor: " + txtValor.getText() + " en: " +  rutaNodo.toString() + System.lineSeparator());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            TreeSelectionModel tsm = jtArbol.getSelectionModel();
            if (tsm.getSelectionCount() <= 0) {
                throw new Exception("¡Ningún nodo para eliminar!");
            }

            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jtArbol.getSelectionPath().getLastPathComponent();

            TreePath rutaNodo = new TreePath(nodoSeleccionado.getPath());

            DefaultTreeModel modeloArbol = (DefaultTreeModel) jtArbol.getModel();
            modeloArbol.removeNodeFromParent(nodoSeleccionado);
            modeloArbol.reload();

            jtArbol.setSelectionPath(rutaNodo);
            jtArbol.expandPath(rutaNodo);


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try{
            
            if(txtValor.getText().length() <= 0)
                throw new Exception("¡Ingrese un valor!");
            
            if(jtArbol.getModel().getRoot() == null)
                throw new Exception("¡El árbol está vacío!");
            
            DefaultMutableTreeNode nodoEncontrado = null;
            DefaultMutableTreeNode nodoRaiz = (DefaultMutableTreeNode) jtArbol.getModel().getRoot();
            
            for (Enumeration e = nodoRaiz.depthFirstEnumeration(); e.hasMoreElements() && nodoEncontrado == null;) 
            {
                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) e.nextElement();                
                if (txtValor.getText().equals(nodo.getUserObject().toString())) {
                    nodoEncontrado = nodo;
                }
            }
            
            if(nodoEncontrado == null)
            {
                JOptionPane.showMessageDialog(null, "El valor no existe en el árbol");
                return;
            }
            
            TreePath rutaNodo = new TreePath(nodoEncontrado.getPath());
            jtArbol.setSelectionPath(rutaNodo);
            jtArbol.expandPath(rutaNodo);

            //txtConsola.setText(txtConsola.getText() + "Nodo buscado " + nodoEncontrado.getUserObject().toString() + " en: " +  rutaNodo.toString() + System.lineSeparator());
                
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTree jtArbol;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
